sonar.projectKey=robbytjhie_msf
sonar.organization=robbytjhie
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src/main,frontend-react/src,auth-node
sonar.tests=backend/src/test
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend-react/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.min.js
